### ISSUE TITLE
how do you download it?

### ISSUE THREAD

**Issue by DOOMMARINE117** [ExelentOS/ExelentOS-iso#6]
i cant find the iso file. 

how to downlaod the iso?

**Comment by NEOLabs-software** [comment]
currently we are fixing a bug with the iso using wayland instead of xorg

I will update the website, 
anyways: https://www.mediafire.com/file/i6waqgs7639rx7m/andromeda-x86_64.iso/file

**Comment by DOOMMARINE117** [comment]
> currently we are fixing a bug with the iso using wayland instead of xorg
> 
> I will update the website, anyways: https://www.mediafire.com/file/i6waqgs7639rx7m/andromeda-x86_64.iso/file

cool. wilthis be updated to 6.5 linux kernel?

**Comment by NEOLabs-software** [comment]
em, not for this release

i mean you can update within the os, but I rather do it with the next release to not break anything
:)

**Comment by DOOMMARINE117** [comment]
> em, not for this release
> 
> i mean you can update within the os, but I rather do it with the next release to not break anything :)

cool, i wait for the next release then. that be easier. 


there's also 6.6 and 6.7. but i was told they dont have much changes.

**Comment by NEOLabs-software** [comment]
good to know...

next release, will be in a WHILE
just so you know

**Comment by DOOMMARINE117** [comment]
> good to know...
> 
> next release, will be in a WHILE just so you know

no problem.
